[pytest]
addopts = --random-order
{% if cookiecutter.database != "none" %}
env =
    DATABASE_URL={% if cookiecutter.database == "sqlite" %}sqlite:///:memory:{% elif cookiecutter.database == "postgresql" %}postgresql://postgres:postgres@localhost:5432/{{ cookiecutter.project_slug }}_test{% endif %}
{% endif %}
